version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: my-movie-book-postgres
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_movie_book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=java
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    container_name: my-movie-book-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_movie_book
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: my-movie-book-frontend
    environment:
      - REACT_APP_HOST=10.60.255.104:8080     #Change it to your machine IP or localhost:8080
      - REACT_APP_HTTP_PROTOCOL=http
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
