version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema-app-postgres
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_movie_book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=java
  backend:
    build: ./cinema-app-backend
    container_name: cinema-app-backend
    environment:
      - DB_SERVER=postgres
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_movie_book
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./cinema-app-frontend
    container_name: cinema-app-frontend
    environment:
      - REACT_APP_HOST=localhost:8080
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
