### POST Movie 1
POST {{host}}/movies
Content-Type: application/json

{
  "title": "Stardust",
  "releaseYear": 2007,
  "genre": "Fantasy",
  "director": "Matthew Vaughn"
}

### GET Movies
GET {{host}}/movies

### GET Movie
GET {{host}}/movies/1
