### GET FilmwebINFO Władca Pierścieni EP_1
GET {{host}}/externalMoviesPage/filmweb/W%C5%82adca+Pier%C5%9Bcieni%3A+Dru%C5%BCyna+Pier%C5%9Bcienia-2001-1065

### GET FilmwebINFO Gwiezdny Pył
GET {{host}}/externalMoviesPage/filmweb/Gwiezdny+py%C5%82-2007-273934