### GET FilmwebINFO Władca Pierścieni EP_1
GET {{host}}/externalMovieData/filmweb/W%C5%82adca+Pier%C5%9Bcieni%3A+Dru%C5%BCyna+Pier%C5%9Bcienia-2001-1065

### GET FilmwebINFO Gwiezdny Pył
GET {{host}}/externalMovieData/filmweb/Gwiezdny+py%C5%82-2007-273934

### GET FilmwebINFO Szkoła uczuć
GET {{host}}/externalMovieData/filmweb/Szkoła+uczuć-2002-33295