### POST Movie 1
POST {{host}}/movies
Content-Type: application/json

{
  "title": "Stardust",
  "releaseYear": 2007,
  "genre": "Fantasy",
  "director": "Matthew Vaughn",
  "posterFileName": "stardust.jpg"
}

### POST Movie 2
POST {{host}}/movies
Content-Type: application/json

{
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "releaseYear": 2001,
  "genre": "Fantasy",
  "director": "Peter Jackson",
  "posterFileName": "lotr_1.jpg"
}

### POST Movie 3
POST {{host}}/movies
Content-Type: application/json

{
  "title": "Star Wars: Episode III",
  "releaseYear": 2005,
  "genre": "Sci-Fi",
  "director": "George Lucas",
  "posterFileName": "sw_3.jpg"
}

### GET Movies
GET {{host}}/movies

### GET Movie
GET {{host}}/movies/1
