### POST Movie 1
POST {{host}}/movies
Content-Type: application/json

{
  "title": "Stardust",
  "filmwebRating": 7.3,
  "filmwebNumberOfVotes": 146233,
  "imdbRating": 7.6,
  "imdbNumberOfVotes": 271951,
  "releaseYear": 2007,
  "genre": "Fantasy",
  "director": "Matthew Vaughn",
  "posterFileName": "stardust.jpg",
  "description": "In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star by venturing into the magical realm."
}

### POST Movie 2
POST {{host}}/movies
Content-Type: application/json

{
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "releaseYear": 2001,
  "filmwebRating": 8.0,
  "filmwebNumberOfVotes": 717513,
  "imdbRating": 8.8,
  "imdbNumberOfVotes": 1800000,
  "genre": "Fantasy",
  "director": "Peter Jackson",
  "posterFileName": "lotr_1.jpg",
  "description": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron."
}

### POST Movie 3
POST {{host}}/movies
Content-Type: application/json

{
  "title": "Star Wars: Episode III",
  "releaseYear": 2005,
  "genre": "Sci-Fi",
  "director": "George Lucas",
  "posterFileName": "sw_3.jpg"
}

### PATCH Movie
PATCH {{host}}/movies/2
Content-Type: application/json

{
  "note": "Very good movie."
}


### GET Movies
GET {{host}}/movies

### GET Movie
GET {{host}}/movies/1
