INSERT INTO roles (id, name) VALUES
(1, 'ROLE_USER'),
(2, 'ROLE_ADMIN')
ON CONFLICT (id) DO NOTHING ;


INSERT INTO genres (id, name) VALUES 
(1,'Akcja'),
(2,'Sci-Fi'),
(3,'Thriller'),
(4,'Romans'),
(5,'Przygodowy'),
(6,'Niemy'),
(7,'Melodramat'),
(8,'Kryminał'),
(9,'Komedia'),
(10,'Krótkometrażowy'),
(11,'Horror'),
(12,'Fantasy'),
(13,'Familijny'),
(14,'Dramat'),
(15,'Dokumentalny'),
(16,'Animacja'),
(17,'Wojenny'),
(18,'Western'),
(19,'True crime'),
(20,'Świąteczny'),
(21,'Sztuki walki'),
(22,'Szpiegowski'),
(23,'Surrealistyczny'),
(24,'Sportowy'),
(25,'Sensacyjny'),
(26,'Satyra'),
(27,'Religijny'),
(28,'Psychologiczny'),
(29,'Przyrodniczy'),
(30,'Propagandowy'),
(31,'Polityczny'),
(32,'Poetycki'),
(33,'Obyczajowy'),
(34,'Muzyczny'),
(35,'Musical'),
(36,'Kostiumowy'),
(37,'Komedia rom.'),
(38,'Komedia obycz.'),
(39,'Komedia kryminalna'),
(40,'Katastroficzny'),
(41,'Historyczny'),
(42,'Groteska filmowa'),
(43,'Gangsterski'),
(44,'Film-Noir'),
(45,'Fabularyzowany dok.'),
(46,'Erotyczny'),
(47,'Dreszczowiec'),
(48,'Dramat sądowy'),
(49,'Dramat obyczajowy'),
(50,'Dramat historyczny'),
(51,'Dokumentalizowany'),
(52,'Dla młodzieży'),
(53,'Dla dzieci'),
(54,'Czarna komedia'),
(55,'Biograficzny'),
(56,'Biblijny'),
(57,'Baśń'),
(58,'Anime')
ON CONFLICT (id) DO NOTHING ;
