### GET FilmwebINFO Władca Pierścieni EP_1
GET {{host}}/externalMovieData/filmweb/W%C5%82adca+Pier%C5%9Bcieni%3A+Dru%C5%BCyna+Pier%C5%9Bcienia-2001-1065

### GET FilmwebINFO Gwiezdny Pył
GET {{host}}/externalMovieData/filmweb/Gwiezdny+py%C5%82-2007-273934
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWZXJkdXR0aW8iLCJpYXQiOjE2OTI3ODg4OTQsImV4cCI6MTY5Mjg3NTI5NH0.QMuD_NWQorTI-E2rpF7lD2gASiR8FB-1Gpdpb_ecCIU2mQjA4caLKKJ-63K3AAmU3-zJ1ha4gguIQ3LpZ5_bzQ

### GET FilmwebINFO Szkoła uczuć
GET {{host}}/externalMovieData/filmweb/Szkoła+uczuć-2002-33295
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWZXJkdXR0aW8iLCJpYXQiOjE2NjUzMzU1ODEsImV4cCI6MTY2NTQyMTk4MX0.YTYZRdNhbGu5GIHOIpR4sDtjOYgO3qK7Ic3qqr_MBuUVkCgkkPocHOnrO-KAd_P-xcse88EeCzsBQJQlxaKWAg


### GET imdbRating Władca Pierścieni EP_1
GET {{host}}/externalMovieData/imdb/rating/W%C5%82adca+Pier%C5%9Bcieni%3A+Dru%C5%BCyna+Pier%C5%9Bcienia-2001-1065

### GET imdbRating Szkoła uczuć
GET {{host}}/externalMovieData/imdb/rating/Szkoła+uczuć-2002-33295

### GET imdbRating Gwiezdny pył
GET {{host}}/externalMovieData/imdb/rating/Dobry+rok-2006
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJWZXJkdXR0aW8iLCJpYXQiOjE2ODE0OTI3NjIsImV4cCI6MTY4MTU3OTE2Mn0.TKxM85K2VXdZhou57km1G8hs31yndbNYUqhm96VghV_7UpPF151EgxFf-LEyvhnebch-PLQKkEg7pdNWiDmEzw