name: Build and deploy the app to heroku
on: push

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        working-directory: Cinema-app-backend
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: Cinema-app-backend
        run: pwd && ls -l && ./gradlew build -x test
      - name: Saving JAR
        uses: actions/upload-artifact@v3
        with:
          name: GradleJAR
          path: Cinema-app-backend/build/libs
#  deploy:
#    name: Deploy to heroku
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Loading JAR
#        uses: actions/download-artifact@v3
#        with:
#          name: GradleJAR
#          path: build/libs