name: Test backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  Tests:
    name: Perform tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        working-directory: backend
        run: chmod +x ./gradlew
      - name: Perform Gradle tests
        working-directory: backend
        run: pwd && ls -l && ./gradlew test
